global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pfsense-mcp'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # pfSense MCP Server metrics
  - job_name: 'pfsense-mcp'
    static_configs:
      - targets: ['pfsense-mcp:9090']
    metrics_path: '/metrics'
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
      
  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
      
  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']